[build]
  publish = "build/"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  REACT_APP_MY_APP_NAME="App Display Name"
  REACT_APP_MY_APP_ID="Midtype Project ID"
  REACT_APP_MY_APP_GOOGLE_SIGN_IN_LINK="Google Sign In Redirect URL"
  REACT_APP_STRIPE_PK="Stripe Publishable Key"