[build]
  publish = "build/"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  REACT_APP_MY_APP_NAME="App Display Name"
  REACT_APP_MY_APP_ID="Midtype Project ID"
  REACT_APP_MY_APP_ENDPOINT="https://todooli-pkv6fida6a-uc.a.run.app/graphql"
  REACT_APP_MY_APP_REDIRECT_URL="Where users should be redirected after logging in"
  REACT_APP_STRIPE_PK="Your Stripe publishable key"